### ISSUE TITLE
[FIX] 피드백 반영 수정

### ISSUE THREAD

**Issue by wlgudths** [boostcampaitech7/level2-cv-semanticsegmentation-cv-22-lv3#107]
# **추가된 기능에 대한 설명을 작성하세요**
- [x] 추가 기능은 없습니다.
<br><br>

# **수정해야 할 파일들**
- [x] os.path -> osp
- [x] base_config.yaml 개행 수정 (한줄)
- [x] model_utils.py 라이브러리 임포트, 코드 개행, 최대 글자 수 79자 통일
- [x] model의 수 많은 config 예시 제외 수정
---
- [x] 디렉토리 이름과 파일명 소문자 변경
- [x] src/Utils/combine_csv_predictions.py 변수명 정돈
- [ ] 절대경로 -> 상대경로
- [x] set_seed.py utils 내의 파일로 합치기
- [x] 입력으로 받는 config의 type을 DictConfig로 통일
<br><br>

# **추가 전달 사항**
- 모든 피드백에 대한 수정 사항은 아닙니다.
- 각자 해당되는 파일에 피드백을 반영하여 수정해주시면 되겠습니다.

**Comment by hanbyeol1001** [comment]
굿이에용
